export const LINKEDIN_ARTICLES = [
  {
    id: 1,
    title: "The Illusion of Control",
    date: "July 13, 2026",
    readTime: "5 min",
    hook: "A single new input can quietly recalibrate an entire system — revealing how tightly you'd been gripping things that were never yours to hold. The question isn't control. It's ownership.",
    pullQuote: "Control often enters disguised as responsibility. Choice disappears quietly, one reasonable decision at a time.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQHW_UB-IRWjUQ/article-cover_image-shrink_720_1280/B56Z72EPdzHUAU-/0/1782244767831?e=1786579200&v=beta&t=NFJYewHSKe4lFn1Sw7Z4k26tkmg76ld15a9y1TtS__c",
    linkedinUrl: "https://www.linkedin.com/pulse/illusion-control-john-thornton-96x1c/",
  },
  {
    id: 2,
    title: "The System Overload Analogy",
    date: "July 6, 2026",
    readTime: "5 min",
    hook: "When a computer slows down, you diagnose the system. When you slow down, you tell yourself to try harder. The logic doesn't hold.",
    pullQuote: "Overload restricts access to intelligence — it doesn't erase it. The question isn't capacity. It's whether you're operating within your designed parameters.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQGWZhWH8BR2Ew/article-cover_image-shrink_720_1280/B56Z72DjNfHYAY-/0/1782244586589?e=2147483647&v=beta&t=fRN-RT-F1Av5gqPMkTCjSAX6i4N0xwKiqO73RkXGbzU",
    linkedinUrl: "https://www.linkedin.com/pulse/system-overload-analogy-john-thornton-oq8ac/",
  },
  {
    id: 3,
    title: "Pressure is a Signal, Not a Test",
    date: "June 29, 2026",
    readTime: "5 min",
    hook: "Tests are meant to be passed. Signals are meant to be read. The moment you confuse the two, endurance becomes a form of avoidance.",
    pullQuote: "Pressure was never designed to be survived. It was designed to communicate.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQHwOg4UFHXR2A/article-cover_image-shrink_720_1280/B56Z72BLLGG0AQ-/0/1782243964459?e=2147483647&v=beta&t=-TCGYdokqGW2W_mKzXwW3grPrP__AwI1itb--N897Ew",
    linkedinUrl: "https://www.linkedin.com/pulse/pressure-signal-test-john-thornton-dpfuc/",
  },
  {
    id: 4,
    title: "The Weight That Doesn't Show",
    date: "June 22, 2026",
    readTime: "5 min",
    hook: "There is a version of fine that doesn't mean fine at all. Bills paid, responsibilities met — and an invisible heaviness in everything.",
    pullQuote: "Functioning and healthy are not the same thing. A system can remain operational through enormous stress — right up until it can't.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQEwsvtnUhW6mw/article-cover_image-shrink_720_1280/B56Z7wAVS1IUAQ-/0/1782143079864?e=2147483647&v=beta&t=o0ieak_3ABNHMbB1ayx8CP0ei_mHM4P8ffv0SgH6fJs",
    linkedinUrl: "https://www.linkedin.com/pulse/weight-doesnt-show-john-thornton-j1oae/",
  },
  {
    id: 5,
    title: 'Your "Normal" is a System Failure',
    date: "June 16, 2026",
    readTime: "5 min",
    hook: "Burnout doesn't announce itself with alarms. It disguises itself as your normal — and that's what makes it dangerous.",
    pullQuote: "If you never audit your settings, that season becomes your life.",
    image: "https://media.licdn.com/dms/image/v2/D5612AQGbFFgjiEj-AQ/article-cover_image-shrink_720_1280/B56Z7RJF88IMAU-/0/1781625282618?e=2147483647&v=beta&t=TGRSL5_gK_OWS9qUNOwBwC9Vrk1KvwlMvj5GCgJHwQQ",
    linkedinUrl: "https://www.linkedin.com/pulse/your-normal-system-failure-why-internal-firewall-leaking-thornton-4ycmc/",
  },
];
